apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: api-service
        image: dvago88/service_a:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9595
        env:
          - name: SERVICEB_URL  
            value: "http://myapp-b-service:9090/hello"
          - name: SERVER_PORT
            value: "9595"