apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b-deployment
spec:
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: dvago88/service_b:latest
        env:
          - name: serviceb.url
            value: "http://service-b:9090"
        ports:
        - containerPort: 9090