apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b-deployment
spec:
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: dvago88/service_b:latest
        env:
          - name: spring.datasource.url
            value: "jdbc:mysql://mysql:3306/spring_boot_db"
          - name: spring.datasource.username
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: username
          - name: spring.datasource.password
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password
        ports:
        - containerPort: 9090 # This should match the port on which Service B is running
